/* to set the computer score and user score to zero */
let userScore = 0;
let compScore=0;

/* accessing all the three rock paper scissor using class choice */
const choices= document.querySelectorAll(".choice");

/* to access the msg paragraph */

const msg=document.querySelector("#msg");


/* acessing user scoreboard and computer scoreboard */

const userScorePara = document.querySelector("#user-score");
const compScorePara = document.querySelector("#computer-score");

/* generate computer choice */

const genCompChoice=()=>{
    const options=["rock","paper","scissors"];
    let randIdx=Math.floor(Math.random()*3);  /* to generate random index range between 0 and 2 */
    return options[randIdx];
}


/* function for draw game */

const drawGame =()=>{
    
    msg.innerText="Game was Draw Play again";
    msg.style.backgroundColor="yellow";
    msg.style.color="black";
}
 const showWinner=(userWin,userChoice,compChoice)=>{
    if(userWin){
       userScore++;
       userScorePara.innerText= userScore;
        msg.innerText=`You Win The Game, ${userChoice} beats ${compChoice}`;
        msg.style.backgroundColor="green";
        msg.style.color="white";
    }
    else{
        compScore++;
        compScorePara.innerText=compScore;
        msg.innerText=`You Lose The Game, ${userChoice} Unbeats ${compChoice}`;
        msg.style.backgroundColor="red";
        msg.style.color="white";
    }
 }

/* function for creating random choice generated by computer  */
 const playGame = (userChoice) =>{
    

    /* generate computer choice */
    const compChoice= genCompChoice();
   


    /* checking the posibilities for winning and losing */
    if(userChoice===compChoice){
        /* draw game */
        drawGame();
    }
    else{
        let userWin= true;
        if (userChoice==="rock"){
            /* scissors, paper */
            userWin=compChoice==="scissors" ? true : false; 
        }
        else if(userChoice==="paper"){
            /* scissors, rock */
            userWin=compChoice==="scissors" ? false : true; 
        }
        else{
            /* rock, paper */
            userWin=compChoice==="rock" ? false : true; 
        }
        showWinner(userWin,userChoice,compChoice);
    }
 }

/* adding  clicking addEventListener for each of them  */
choices.forEach((choice)=>{
    

    choice.addEventListener("click",()=>{
        const userChoice = choice.getAttribute("id"); /* accessing id of each choice  */
         
        playGame(userChoice) /* calling palyGame */
    });
});


